# Generated by Django 4.0.4 on 2022-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('doc_id', models.UUIDField(primary_key=True, serialize=False)),
                ('employer_name', models.CharField(max_length=100)),
                ('date_posted', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
