# Generated by Django 4.0.4 on 2022-09-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='doc_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
