# Generated by Django 4.0.4 on 2022-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_vacancy_description_alter_vacancy_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='doc_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
