# Generated by Django 4.0.4 on 2022-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_date_posted_alter_vacancy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=50000),
        ),
    ]
