# Generated by Django 4.0.4 on 2022-09-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancy',
            table='TB_VACANCY',
        ),
    ]
