# Generated by Django 4.0.4 on 2022-09-03 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=100)),
                ('pass_user', models.CharField(max_length=100)),
                ('email_user', models.CharField(max_length=100)),
            ],
        ),
    ]
