# Generated by Django 4.0.4 on 2022-09-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='TB_USER',
        ),
    ]
